export default {
  Donate: 'Donate',
  Collect: 'Collect',
  Volunteer: 'Volunteer',
  NGO: 'NGO',
  Close: 'Close',
  Ok: 'Ok',
  Yes: 'Yes',
  No: 'No',
  AddProduct: 'Add Product',
  SelectImage: 'Add Image',
  Title: 'Title',
  Description: 'Description',
  ProductCondition: 'Product Condition',
  Products: 'Products',
  MyProducts: 'My Products',
  Category: 'Category',
};
